import { Vendor, Product } from '../types';

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'vendor-gents-wardrobe',
    storeName: 'Gents Wardrobe BD',
    ownerEmail: 'gents.demo@gmail.com',
    ownerUid: 'uid-gents-demo',
    whatsapp: '01711902233',
    category: 'Men\'s Fashion',
    description: 'Premier menswear boutique specializing in premium cotton Panjabis, linen casual shirts, and tailored trousers in Dhaka.',
    district: 'Dhaka',
    address: 'Shop 42, Level 3, Police Plaza Concord, Gulshan 1, Dhaka',
    bannerUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 84500,
    totalOrders: 38,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'vendor-lady-style',
    storeName: 'Lady Style BD',
    ownerEmail: 'ladystyle.demo@gmail.com',
    ownerUid: 'uid-ladystyle-demo',
    whatsapp: '01819445566',
    category: 'Women\'s Fashion',
    description: 'Authentic Tangail & Dhakai Jamdani sarees, boutique kurtis, and designer festive 3-piece sets.',
    district: 'Chittagong',
    address: 'Afmi Plaza, Level 2, Nasirabad, Chittagong',
    bannerUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 112000,
    totalOrders: 45,
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'vendor-chronos-watches',
    storeName: 'Chronos Watches BD',
    ownerEmail: 'chronos.demo@gmail.com',
    ownerUid: 'uid-chronos-demo',
    whatsapp: '01912889900',
    category: 'Watches & Accessories',
    description: '100% genuine wristwatches, chronograph timepieces, and modern AMOLED smartwatches with official warranty.',
    district: 'Sylhet',
    address: 'Al-Hamra Shopping City, Zindabazar, Sylhet',
    bannerUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 154000,
    totalOrders: 52,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'vendor-gadget-sphere',
    storeName: 'Gadget Sphere',
    ownerEmail: 'gadgetsphere.demo@gmail.com',
    ownerUid: 'uid-gadgetsphere-demo',
    whatsapp: '01611334455',
    category: 'Mobile & Electronics',
    description: 'Smart lifestyle gear, wireless earbuds, magnetic power banks, and fast charging docks from global brands.',
    district: 'Dhaka',
    address: 'Eastern Plaza, 4th Floor, Hatirpool, Dhaka',
    bannerUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 198000,
    totalOrders: 89,
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'vendor-footwear-nation',
    storeName: 'Footwear Nation',
    ownerEmail: 'footwearnation.demo@gmail.com',
    ownerUid: 'uid-footwear-demo',
    whatsapp: '01712556677',
    category: 'Footwear',
    description: 'Handcrafted genuine leather formal shoes, breathable running sneakers, and comfortable daily sandals.',
    district: 'Gazipur',
    address: 'Tongi Bazar Commercial Area, Gazipur',
    bannerUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 92000,
    totalOrders: 34,
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    id: 'vendor-organic-food',
    storeName: 'Organic Food BD',
    ownerEmail: 'organicfood.demo@gmail.com',
    ownerUid: 'uid-organic-demo',
    whatsapp: '01815667788',
    category: 'Groceries & Organic',
    description: '100% adulteration-free natural foods: Sundarban floral raw honey, wood-pressed mustard oil, and village cow ghee.',
    district: 'Rajshahi',
    address: 'Shaheb Bazar Zero Point, Rajshahi',
    bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 67000,
    totalOrders: 48,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'vendor-kids-mart',
    storeName: 'Kids Mart BD',
    ownerEmail: 'kidsmart.demo@gmail.com',
    ownerUid: 'uid-kidsmart-demo',
    whatsapp: '01918334422',
    category: 'Baby & Kids',
    description: 'Non-toxic, ultra-soft newborn infant wear, Montessori learning toys, and baby feeding accessories.',
    district: 'Dhaka',
    address: 'Shimanto Square, Dhanmondi 2, Dhaka',
    bannerUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 54000,
    totalOrders: 31,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'vendor-beauty-secrets',
    storeName: 'Beauty Secrets BD',
    ownerEmail: 'beautysecrets.demo@gmail.com',
    ownerUid: 'uid-beauty-demo',
    whatsapp: '01719223311',
    category: 'Beauty & Skincare',
    description: 'Halal, organic, chemical-free herbal skincare formulated for South Asian skin tones and climates.',
    district: 'Bogura',
    address: 'Nawab Bari Road, Bogura Sadar',
    bannerUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 78000,
    totalOrders: 56,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'vendor-home-comforts',
    storeName: 'Home Comforts',
    ownerEmail: 'homecomforts.demo@gmail.com',
    ownerUid: 'uid-home-demo',
    whatsapp: '01811442299',
    category: 'Home & Living',
    description: '300TC Egyptian cotton bed linens, cozy handloom throw cushions, and modern modular kitchen storage.',
    district: 'Cumilla',
    address: 'Kandirpar Commercial Complex, Cumilla',
    bannerUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 89000,
    totalOrders: 33,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'vendor-tech-hub',
    storeName: 'Tech Hub BD',
    ownerEmail: 'techhub.demo@gmail.com',
    ownerUid: 'uid-techhub-demo',
    whatsapp: '01619887700',
    category: 'Computer & Peripherals',
    description: 'Mechanical hot-swappable keyboards, lightweight esports mice, condenser microphones, and desk mats.',
    district: 'Dhaka',
    address: 'Multiplan Center, New Elephant Road, Dhaka',
    bannerUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=1200&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
    isDemo: true,
    isApproved: true,
    isBlocked: false,
    totalSales: 165000,
    totalOrders: 64,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const DEMO_PRODUCTS: Product[] = [
  // 1. Gents Wardrobe
  {
    id: 'prod-gents-panjabi-01',
    vendorId: 'vendor-gents-wardrobe',
    storeName: 'Gents Wardrobe BD',
    title: 'Premium Egyptian Cotton Embroidered Panjabi - Royal Navy',
    description: 'Crafted from 100% superfine combed Egyptian cotton. Features intricate minimal embroidery on collar and placket with mother-of-pearl buttons. Ideal for Friday prayers, Eid festivals, and formal weddings.',
    category: 'Men\'s Fashion',
    price: 2850,
    discountPrice: 2450,
    stock: 25,
    primaryImage: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=800&auto=format&fit=crop&q=80',
    tags: ['Panjabi', 'Cotton', 'Navy Blue', 'Eid Collection', 'Menswear'],
    isDemo: true,
    status: 'active',
    rating: 4.9,
    reviewsCount: 18,
    seo: {
      metaTitle: 'Premium Egyptian Cotton Panjabi Navy Blue | Gents Wardrobe BD',
      metaDescription: 'Buy authentic Egyptian Cotton Embroidered Panjabi online at Best Price ৳2450 in Bangladesh. Fast home delivery across BD.',
      altText: 'Premium Egyptian Cotton Embroidered Panjabi Royal Navy',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-gents-shirt-02',
    vendorId: 'vendor-gents-wardrobe',
    storeName: 'Gents Wardrobe BD',
    title: 'Pure Linen Slim Fit Casual Shirt - Sky Blue',
    description: 'Ultra-breathable 100% natural European linen fabric tailored for humid tropical Bangladeshi weather. Pre-washed for soft hand-feel.',
    category: 'Men\'s Fashion',
    price: 1850,
    discountPrice: 1590,
    stock: 40,
    primaryImage: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    tags: ['Linen Shirt', 'Casual', 'Summer Wear', 'Sky Blue'],
    isDemo: true,
    status: 'active',
    rating: 4.8,
    reviewsCount: 12,
    seo: {
      metaTitle: 'Pure Linen Slim Fit Casual Shirt Sky Blue | Dokani Bangladesh',
      metaDescription: 'Order pure linen casual shirt for men online at ৳1590 from Gents Wardrobe. 100% genuine fabric.',
      altText: 'Pure Linen Slim Fit Casual Shirt Sky Blue',
    },
    createdAt: new Date().toISOString(),
  },

  // 2. Lady Style BD
  {
    id: 'prod-lady-jamdani-01',
    vendorId: 'vendor-lady-style',
    storeName: 'Lady Style BD',
    title: 'Traditional Handwoven Dhakai Jamdani Saree - Golden Cream',
    description: 'Heritage 84-count fine cotton handloom Jamdani saree woven by master artisans in Narayanganj. Features traditional floral Jaal motifs with matching unstitched blouse piece.',
    category: 'Women\'s Fashion',
    price: 6800,
    discountPrice: 5950,
    stock: 12,
    primaryImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    tags: ['Jamdani', 'Saree', 'Handloom', 'Wedding', 'Dhakai'],
    isDemo: true,
    status: 'active',
    rating: 5.0,
    reviewsCount: 22,
    seo: {
      metaTitle: 'Original Dhakai Jamdani Saree Golden Cream | Lady Style BD',
      metaDescription: 'Shop authentic handwoven Dhakai Jamdani saree online at ৳5950. Direct from weavers, delivered all over Bangladesh.',
      altText: 'Handwoven Dhakai Jamdani Saree Golden Cream',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-lady-kurti-02',
    vendorId: 'vendor-lady-style',
    storeName: 'Lady Style BD',
    title: 'Floral Hand-Block Printed Cotton Kurti Set',
    description: 'Chic 2-piece set including A-line block printed cotton kurti with matching cigarette pants. Comfort fit for daily university and office wear.',
    category: 'Women\'s Fashion',
    price: 2150,
    discountPrice: 1790,
    stock: 35,
    primaryImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    tags: ['Kurti', 'Block Print', 'Cotton', 'Summer Fashion'],
    isDemo: true,
    status: 'active',
    rating: 4.7,
    reviewsCount: 15,
    seo: {
      metaTitle: 'Floral Hand Block Printed Cotton Kurti Set | Lady Style BD',
      metaDescription: 'Buy designer cotton kurti set online at ৳1790. Premium comfort and vibrant colors.',
      altText: 'Floral Hand-Block Printed Cotton Kurti Set',
    },
    createdAt: new Date().toISOString(),
  },

  // 3. Chronos Watches
  {
    id: 'prod-watch-naviforce-01',
    vendorId: 'vendor-chronos-watches',
    storeName: 'Chronos Watches BD',
    title: 'Chronos Aviator Chronograph Stainless Steel Wristwatch',
    description: 'Japanese quartz movement with functioning sub-dials, date window, hardened mineral glass, and 30m water resistance. Comes with 1-year official warranty and luxury presentation box.',
    category: 'Watches & Accessories',
    price: 3450,
    discountPrice: 2890,
    stock: 20,
    primaryImage: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
    tags: ['Watch', 'Chronograph', 'Stainless Steel', 'Men Watch'],
    isDemo: true,
    status: 'active',
    rating: 4.9,
    reviewsCount: 31,
    seo: {
      metaTitle: 'Chronos Aviator Chronograph Stainless Steel Watch | Dokani',
      metaDescription: 'Get original Chronos Aviator Chronograph Watch at ৳2890 with 1-year warranty. Fast cash on delivery in BD.',
      altText: 'Chronos Aviator Chronograph Stainless Steel Wristwatch',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-watch-smart-02',
    vendorId: 'vendor-chronos-watches',
    storeName: 'Chronos Watches BD',
    title: 'Aura Pulse AMOLED Smartwatch with Bluetooth Calling',
    description: '1.43-inch HD AMOLED Always-On display, zinc alloy body, 24/7 heart rate and SpO2 monitor, Bangla notifications support, and 7-day battery life.',
    category: 'Watches & Accessories',
    price: 4200,
    discountPrice: 3490,
    stock: 18,
    primaryImage: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80',
    tags: ['Smartwatch', 'AMOLED', 'Fitness Tracker', 'Bluetooth Call'],
    isDemo: true,
    status: 'active',
    rating: 4.8,
    reviewsCount: 27,
    seo: {
      metaTitle: 'Aura Pulse AMOLED Smartwatch Bluetooth Calling | Chronos BD',
      metaDescription: 'Shop Aura Pulse AMOLED Smartwatch online at ৳3490. Bangla language support, 7-day battery.',
      altText: 'Aura Pulse AMOLED Smartwatch with Bluetooth Calling',
    },
    createdAt: new Date().toISOString(),
  },

  // 4. Gadget Sphere
  {
    id: 'prod-gadget-earbuds-01',
    vendorId: 'vendor-gadget-sphere',
    storeName: 'Gadget Sphere',
    title: 'SoundWave ANC Wireless Earbuds with Quad Mic ENC',
    description: '35dB Active Noise Cancellation, 13mm titanium dynamic drivers for punchy bass, Bluetooth 5.3 low latency gaming mode, and 38-hour total playtime with USB-C case.',
    category: 'Mobile & Electronics',
    price: 2600,
    discountPrice: 2150,
    stock: 50,
    primaryImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    tags: ['TWS', 'Earbuds', 'ANC', 'Wireless Audio', 'Bluetooth 5.3'],
    isDemo: true,
    status: 'active',
    rating: 4.8,
    reviewsCount: 42,
    seo: {
      metaTitle: 'SoundWave ANC Wireless Earbuds Quad Mic ENC | Gadget Sphere',
      metaDescription: 'Buy SoundWave ANC TWS Earbuds at ৳2150. Active noise cancelling and 38h battery life.',
      altText: 'SoundWave ANC Wireless Earbuds with Quad Mic ENC',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-gadget-powerbank-02',
    vendorId: 'vendor-gadget-sphere',
    storeName: 'Gadget Sphere',
    title: 'VoltPro 20000mAh 22.5W Fast Charging Power Bank',
    description: 'Dual USB-A and PD 20W Type-C output, digital LED percentage indicator, airline safe, supports Quick Charge 3.0 and Huawei FCP.',
    category: 'Mobile & Electronics',
    price: 2400,
    discountPrice: 1950,
    stock: 35,
    primaryImage: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
    tags: ['Powerbank', '20000mAh', 'Fast Charging', 'USB-C PD'],
    isDemo: true,
    status: 'active',
    rating: 4.9,
    reviewsCount: 38,
    seo: {
      metaTitle: 'VoltPro 20000mAh 22.5W Power Bank | Gadget Sphere BD',
      metaDescription: 'Order 20000mAh fast charge power bank online at ৳1950. Fast delivery across Bangladesh.',
      altText: 'VoltPro 20000mAh 22.5W Fast Charging Power Bank',
    },
    createdAt: new Date().toISOString(),
  },

  // 5. Footwear Nation
  {
    id: 'prod-shoe-oxford-01',
    vendorId: 'vendor-footwear-nation',
    storeName: 'Footwear Nation',
    title: 'Genuine Full-Grain Leather Cap-Toe Oxford Shoes - Mahogany',
    description: 'Handmade by heritage artisans in Gazipur using top-tier cowhide leather. Cushioned memory foam insole and slip-resistant rubber outsole.',
    category: 'Footwear',
    price: 4200,
    discountPrice: 3650,
    stock: 22,
    primaryImage: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80',
    tags: ['Leather Shoes', 'Oxford', 'Formal', 'Mahogany', 'Handmade'],
    isDemo: true,
    status: 'active',
    rating: 4.9,
    reviewsCount: 19,
    seo: {
      metaTitle: 'Genuine Leather Oxford Shoes Mahogany | Footwear Nation',
      metaDescription: 'Buy 100% original full-grain leather oxford shoes at ৳3650. Handcrafted comfort in BD.',
      altText: 'Genuine Full-Grain Leather Cap-Toe Oxford Shoes',
    },
    createdAt: new Date().toISOString(),
  },

  // 6. Organic Food BD
  {
    id: 'prod-organic-honey-01',
    vendorId: 'vendor-organic-food',
    storeName: 'Organic Food BD',
    title: 'Pure Sundarban Khalisha Wildflower Raw Honey - 500g',
    description: '100% natural, unprocessed raw honey collected directly by Moulis from Sundarban deep mangroves. Certified pure, rich in natural pollen, enzymes, and antioxidants.',
    category: 'Groceries & Organic',
    price: 950,
    discountPrice: 790,
    stock: 60,
    primaryImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
    tags: ['Honey', 'Sundarban', 'Organic', 'Natural Food', 'Raw Honey'],
    isDemo: true,
    status: 'active',
    rating: 5.0,
    reviewsCount: 54,
    seo: {
      metaTitle: 'Pure Sundarban Wild Honey 500g | Organic Food BD',
      metaDescription: 'Buy 100% original Sundarban wildflower raw honey at ৳790. Lab-tested pure honey in Bangladesh.',
      altText: 'Pure Sundarban Khalisha Wildflower Raw Honey',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-organic-ghee-02',
    vendorId: 'vendor-organic-food',
    storeName: 'Organic Food BD',
    title: 'Traditional Deshi Cow Danadar Ghee - 450g',
    description: 'Cultured cow milk butter slowly clarified over wood fire. Rich aroma, granular (danadar) texture, zero preservatives.',
    category: 'Groceries & Organic',
    price: 1250,
    discountPrice: 1050,
    stock: 45,
    primaryImage: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80',
    tags: ['Ghee', 'Deshi Ghee', 'Danadar', 'Organic Food'],
    isDemo: true,
    status: 'active',
    rating: 5.0,
    reviewsCount: 39,
    seo: {
      metaTitle: 'Deshi Cow Danadar Ghee 450g | Organic Food BD',
      metaDescription: 'Buy authentic wood-fired deshi cow ghee at ৳1050. Pure village ghee delivery across BD.',
      altText: 'Traditional Deshi Cow Danadar Ghee',
    },
    createdAt: new Date().toISOString(),
  },

  // 7. Kids Mart BD
  {
    id: 'prod-kids-romper-01',
    vendorId: 'vendor-kids-mart',
    storeName: 'Kids Mart BD',
    title: 'Soft Organic Cotton 3-Piece Baby Romper Gift Set',
    description: 'Hypoallergenic 100% combed organic cotton baby set with nickel-free snaps. Includes bodysuit, matching cap, and booties.',
    category: 'Baby & Kids',
    price: 1350,
    discountPrice: 1100,
    stock: 30,
    primaryImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
    tags: ['Baby Clothes', 'Romper', 'Organic Cotton', 'Infant Gift'],
    isDemo: true,
    status: 'active',
    rating: 4.9,
    reviewsCount: 21,
    seo: {
      metaTitle: 'Organic Cotton 3-Piece Baby Romper Set | Kids Mart BD',
      metaDescription: 'Buy soft organic cotton infant romper set at ৳1100. Safe and gentle for newborn babies.',
      altText: 'Soft Organic Cotton 3-Piece Baby Romper Gift Set',
    },
    createdAt: new Date().toISOString(),
  },

  // 8. Beauty Secrets BD
  {
    id: 'prod-beauty-serum-01',
    vendorId: 'vendor-beauty-secrets',
    storeName: 'Beauty Secrets BD',
    title: 'Kashmiri Saffron & 24K Gold Glowing Face Serum - 30ml',
    description: 'Enriched with authentic Kashmiri saffron, sweet almond oil, and pure 24K gold flakes. Reduces dark spots, evens skin tone, and hydrates dry skin.',
    category: 'Beauty & Skincare',
    price: 1650,
    discountPrice: 1350,
    stock: 40,
    primaryImage: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80',
    tags: ['Serum', 'Saffron', 'Glowing Skin', 'Halal Skincare'],
    isDemo: true,
    status: 'active',
    rating: 4.8,
    reviewsCount: 35,
    seo: {
      metaTitle: 'Kashmiri Saffron 24K Gold Face Serum | Beauty Secrets BD',
      metaDescription: 'Buy organic Kashmiri saffron glow serum at ৳1350. Chemical-free brightening skincare in BD.',
      altText: 'Kashmiri Saffron and 24K Gold Glowing Face Serum',
    },
    createdAt: new Date().toISOString(),
  },

  // 9. Home Comforts
  {
    id: 'prod-home-bedsheet-01',
    vendorId: 'vendor-home-comforts',
    storeName: 'Home Comforts',
    title: '100% Pure Combed Cotton King Size Bedsheet with 2 Pillow Covers',
    description: '300 Thread Count sateen weave cotton. Color-fast reactive dyes that withstand numerous machine washes without fading. Fits 7ft x 8ft king size beds.',
    category: 'Home & Living',
    price: 2450,
    discountPrice: 1990,
    stock: 28,
    primaryImage: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
    tags: ['Bedsheet', 'Cotton', 'King Size', 'Home Decor'],
    isDemo: true,
    status: 'active',
    rating: 4.7,
    reviewsCount: 24,
    seo: {
      metaTitle: 'Pure Cotton King Size Bedsheet Set | Home Comforts BD',
      metaDescription: 'Order 300TC cotton king bedsheet set online at ৳1990. Soft, durable and color guaranteed.',
      altText: 'Pure Combed Cotton King Size Bedsheet with 2 Pillow Covers',
    },
    createdAt: new Date().toISOString(),
  },

  // 10. Tech Hub BD
  {
    id: 'prod-tech-keyboard-01',
    vendorId: 'vendor-tech-hub',
    storeName: 'Tech Hub BD',
    title: 'AuraMech K68 Hot-Swappable RGB Mechanical Gaming Keyboard',
    description: 'Compact 65% wireless layout with Bluetooth 5.0, 2.4G dongle, and Type-C wired modes. Pre-lubed Gateron Yellow switches, sound-dampening silicone foam, and per-key RGB backlighting.',
    category: 'Computer & Peripherals',
    price: 4600,
    discountPrice: 3890,
    stock: 20,
    primaryImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    tags: ['Keyboard', 'Mechanical Keyboard', 'RGB', 'Gaming', 'Hot Swap'],
    isDemo: true,
    status: 'active',
    rating: 5.0,
    reviewsCount: 47,
    seo: {
      metaTitle: 'AuraMech K68 Hot Swappable RGB Mechanical Keyboard | Tech Hub',
      metaDescription: 'Buy wireless hot-swappable mechanical gaming keyboard at ৳3890 in BD. 1-year replacement warranty.',
      altText: 'AuraMech K68 Hot-Swappable RGB Mechanical Gaming Keyboard',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-tech-mouse-02',
    vendorId: 'vendor-tech-hub',
    storeName: 'Tech Hub BD',
    title: 'AeroGlide Ultra-Lightweight 58g Gaming Mouse - 16000 DPI',
    description: 'PixArt 3389 flagship optical sensor, ultra-flexible paracord cable, PTFE virgin glide skates, and Omron 50M click switches.',
    category: 'Computer & Peripherals',
    price: 2200,
    discountPrice: 1790,
    stock: 35,
    primaryImage: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    tags: ['Gaming Mouse', 'Lightweight', '16000 DPI', 'RGB'],
    isDemo: true,
    status: 'active',
    rating: 4.8,
    reviewsCount: 29,
    seo: {
      metaTitle: 'AeroGlide Lightweight 58g Gaming Mouse | Tech Hub BD',
      metaDescription: 'Shop 58g esports optical gaming mouse at ৳1790. High precision PixArt sensor.',
      altText: 'AeroGlide Ultra-Lightweight 58g Gaming Mouse',
    },
    createdAt: new Date().toISOString(),
  },
];
